name: primware
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  top_snackbar_flutter: ^3.2.0
  intl: ^0.20.2
  dropdown_search: ^6.0.2
  searchfield: ^1.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
